### ISSUE TITLE
Give users an example structure to use if they say !credits and provide no other params

### ISSUE THREAD

**Issue by Sylk** [Sylk/dragon-hoard#2]
When a user says in chat `!credits` detect it, and then display the arguments and the structure of the string that needs to be passed in.

Structure is currently documented but, for sake of not leaving the page the structure is as follow.

`!credits creditOperator taggedUser creditAmount`

The options for creditOperator as of now are: `give, request, destroy, rob`
The parameter of taggedUser must be a unique discord snowflake ID that's in the server
The credit amount must be greater than 0 and an integer

**Comment by faulted** [comment]
Completed this issue #6
